version: '3'

services:
  postgres:
    image: 'postgres:10.5'
    container_name: 'app-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=Tommishelby04'
      - 'POSTGRES_DB=springjpa'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      -  '8080:8080'